<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="1" tests="1" time="3.3493568897247314">
	<testsuite disabled="0" errors="0" failures="1" name="meraki_site_to_site_vpn-p4kv9300" skipped="0" tests="1" time="3.3493568897247314">
		<testcase classname="/root/ansible/ansible_collections/cisco/meraki/tests/output/.tmp/integration/meraki_site_to_site_vpn-peborkdv-ÅÑŚÌβŁÈ/tests/integration/targets/meraki_site_to_site_vpn/tasks/main.yml:7" name="[localhost] meraki: meraki_site_to_site_vpn : Query all rules auth_key={{auth_key}}, state=query, org_name={{test_org_name}}, net_name={{test_net_name}}" time="3.349357">
			<failure message="No network found with the name Home - Appliance" type="failure">{
&quot;ansible_facts&quot;: {
&quot;discovered_interpreter_python&quot;: &quot;/usr/bin/python&quot;
},
&quot;changed&quot;: false,
&quot;deprecations&quot;: [
{
&quot;msg&quot;: &quot;Distribution Ubuntu 18.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information&quot;,
&quot;version&quot;: &quot;2.12&quot;
}
],
&quot;msg&quot;: &quot;No network found with the name Home - Appliance&quot;,
&quot;response&quot;: &quot;OK (unknown bytes)&quot;,
&quot;status&quot;: 200
}</failure>
		</testcase>
	</testsuite>
</testsuites>
